# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
labels:
  org.opencontainers.image.title: "Liam yoto sync tool"
  org.opencontainers.image.description: "Liams yoto sync tool"
  org.opencontainers.image.source: "https://github.com/ramesius/ha-addons"
  org.opencontainers.image.licenses: "Proprietary"
args:
  TEMPIO_VERSION: "2021.09.0"